imports:
  - { resource: ../../../src/Backoffice/Shared/Infrastructure/Symfony/DependencyInjection/backoffice_services.yaml }

services:
  _defaults:
    autoconfigure: true
    autowire: true

  # Configure
  _instanceof:

    RaspinuOffice\Shared\Domain\Bus\Command\CommandHandler:
      tags: ['codely.command_handler']

    RaspinuOffice\Shared\Domain\Bus\Query\QueryHandler:
      tags: ['codely.query_handler']

  RaspinuOffice\Apps\Backoffice\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']


  # Wire
  RaspinuOffice\Shared\:
    resource: '../../../src/Shared'

  RaspinuOffice\Backoffice\:
    resource: '../../../src/Backoffice'

  # -- TAGGING --
  RaspinuOffice\Shared\Infrastructure\Bus\Event\InMemory\InMemorySymfonyEventBus:
    arguments: [!tagged codely.domain_event_subscriber]
    lazy: true

  RaspinuOffice\Shared\Infrastructure\Doctrine\DatabaseConnections:
    arguments: [!tagged codely.database_connection]


  # -- APP DEFINITIONS --
  # Command/Query Handlers
  RaspinuOffice\Shared\Infrastructure\Bus\Command\InMemorySymfonyCommandBus:
    arguments: [!tagged codely.command_handler]

  RaspinuOffice\Shared\Infrastructure\Bus\Query\InMemorySymfonyQueryBus:
    arguments: [!tagged codely.query_handler]
