doctrine:
    dbal:

        default_connection: default
        connections:
            default:
                driver: pdo_mysql
                url: '%env(resolve:DATABASE_URL)%'
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'

        types:
#            gener_id:
#                class: ApiInmuebles\Backoffice\Products\Gener\Infrastructure\Persistence\Doctrine\Type\GenerIdType
#            label_id:
#                class: ApiInmuebles\Backoffice\Products\Label\Infrastructure\Persistence\Doctrine\Type\LabelIdType
#            label_name:
#                class: ApiInmuebles\Backoffice\Products\Label\Infrastructure\Persistence\Doctrine\Type\LabelNameType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
#            gener:
#                mapping: true
#                type: yml
#                dir: '%kernel.project_dir%/src/Backoffice/Products/Gener/Infrastructure/Persistence/Doctrine/Mapping'
#                prefix: 'ApiInmuebles\Backoffice\Products\Gener\Domain'
#                alias: gener
#
#            label:
#                mapping: true
#                type: yml
#                dir: '%kernel.project_dir%/src/Backoffice/Products/Label/Infrastructure/Persistence/Doctrine/Mapping'
#                prefix: 'ApiInmuebles\Backoffice\Products\Label\Domain'
#                alias: label
