doctrine:
    dbal:

        default_connection: default
        connections:
            default:
                driver: pdo_mysql
                url: '%env(resolve:DATABASE_URL)%'
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'

        types:
            ### Property
            property_id:
                class: ApiInmuebles\Backoffice\Commercial\Property\Infrastructure\Persistence\Doctrine\Type\PropertyIdType
            property_title:
                class: ApiInmuebles\Backoffice\Commercial\Property\Infrastructure\Persistence\Doctrine\Type\PropertyTitleType
            property_description:
                class: ApiInmuebles\Backoffice\Commercial\Property\Infrastructure\Persistence\Doctrine\Type\PropertyDescriptionType
            property_tours_collection:
                class: ApiInmuebles\Backoffice\Commercial\Property\Infrastructure\Persistence\Doctrine\Type\PropertyToursCollectionType

            ### Tour
            tour_id:
                class: ApiInmuebles\Backoffice\Commercial\Tour\Infrastructure\Persistence\Doctrine\Type\TourIdType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            property:
                mapping: true
                type: yml
                dir: '%kernel.project_dir%/src/Backoffice/Commercial/Property/Infrastructure/Persistence/Doctrine/Mapping'
                prefix: 'ApiInmuebles\Backoffice\Commercial\Property\Domain'
                alias: property

            tour:
                mapping: true
                type: yml
                dir: '%kernel.project_dir%/src/Backoffice/Commercial/Tour/Infrastructure/Persistence/Doctrine/Mapping'
                prefix: 'ApiInmuebles\Backoffice\Commercial\Tour\Domain'
                alias: tour
