twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    globals:
        kernelRootDir: "%kernel.project_dir%"
        publicDir: "%kernel.project_dir%/public"
        env: "%env%"
