doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'

    # IMPORTANT: You MUST configure your server version,
    # either here or in the DATABASE_URL env var (see .env file)
    server_version: '8'
    charset: UTF8
    types:
      gener_id:
        class: RaspinuOffice\Backoffice\Products\Gener\Infrastructure\Doctrine\Type\GenerIdType
  orm:
    auto_generate_proxy_classes: true
      naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
      auto_mapping: true
      mappings:
        gener:
          mapping: true
          type: yml
          dir: '%kernel.project_dir%/src/Backoffice/Products/Gener/Infrastructure/Persistence/Doctrine/Mapping'
          prefix: 'RaspinuOffice\Backoffice\Products\Gener\Domain'
          alias: gener

